# Typed surface of the tirocinium_mastery extension module
# (crates/platform_core/mastery/src/python.rs). Kept in lockstep with the
# Rust bindings by hand; the boundary is JSON strings in, JSON strings out.

SPEC_VERSION: str

def default_params_json() -> str: ...
def apply_json(state_json: str | None, event_json: str, params_json: str) -> str: ...
def replay_json(events_json: str, params_json: str) -> str | None: ...
def supersede_json(events_json: str) -> str: ...
def view_json(state_json: str, now: int, params_json: str) -> str: ...
