#!/usr/bin/env bash
# Build the server env file from the local one, carrying across the values that
# are the same everywhere and refusing to carry the ones that are not.
#
# The provider keys and the model pins are account-level facts: the same
# Anthropic key works from a laptop and from EC2, and a model id pinned in
# development is the one the deployment should run. Those are copied.
#
# Nothing else is. The JWT secret is regenerated, because a secret that has
# lived on a development machine signs tokens that would then be valid in
# production, and the point of the secret is that only the server knows it. The
# storage settings are rewritten, because local runs talk to MinIO on loopback
# and the deployment talks to S3. The data directory is rewritten, because local
# runs keep shards under the repo and the deployment keeps them on the volume
# that survives the instance.
#
# Usage: infra/deploy/build-server-env.sh [output-path]
# Writes a 0600 file outside the repository and prints the key names it filled.
# It never prints a value.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
local_env="$repo_root/apps/api/.env"
out="${1:-$HOME/tirocinium.env}"

[ -f "$local_env" ] || { echo "no $local_env to read from" >&2; exit 1; }
case "$(cd "$(dirname "$out")" && pwd)" in
  "$repo_root"|"$repo_root"/*)
    echo "refusing to write $out inside the repository (decision 0092)" >&2
    exit 1 ;;
esac

# Read one key's value out of the local env, ignoring commented lines.
local_value() {
  sed -nE "s/^[[:space:]]*$1=(.*)$/\1/p" "$local_env" | tail -1
}

# Account-level values: the same from anywhere, so they travel.
CARRY=(
  TIRO_ANTHROPIC_API_KEY TIRO_OPENAI_API_KEY
  TIRO_STT_PROVIDER TIRO_DEEPGRAM_API_KEY
  TIRO_TTS_PROVIDER TIRO_CARTESIA_API_KEY TIRO_CARTESIA_VOICE TIRO_CARTESIA_URL
  TIRO_VISION_MODEL_ID TIRO_SEGMENTATION_MODEL_ID TIRO_PROPOSAL_MODEL_ID
  TIRO_GENERATION_MODEL_ID TIRO_VERIFICATION_MODEL_ID TIRO_ASSESSMENT_MODEL_ID
  TIRO_EMBEDDING_MODEL_ID TIRO_TUTOR_MODEL_ID TIRO_RUBRIC_MODEL_ID
)

umask 077
: > "$out"

{
  echo "# Tirocinium server environment. Generated by infra/deploy/build-server-env.sh."
  echo "# Install as /etc/tirocinium/tirocinium.env, root:tirocinium, mode 0640."
  echo
  echo "# Host settings. These differ from a development machine by design."
  echo "TIRO_DATA_DIR=/var/lib/tirocinium/data"
  echo "# Empty means real AWS, which picks the regional endpoint and the"
  echo "# addressing style S3 wants. Set it only for a MinIO-compatible server."
  echo "TIRO_S3_ENDPOINT="
  echo "TIRO_S3_REGION=ca-central-1"
  echo "TIRO_SCANS_BUCKET=tirocinium-scans"
  echo "TIRO_IMPORTS_BUCKET=tirocinium-imports"
  echo "TIRO_ARTIFACT_BUCKET=tirocinium-artifacts"
  echo "TIRO_REDIS_URL=redis://127.0.0.1:6379"
  echo "TIRO_PDFIUM_LIB=/opt/tirocinium/pdfium/lib/libpdfium.so"
  echo "TIRO_SIGNUP_ALLOWLIST=ebenezer.kwofie@mcgill.ca"
  echo
  echo "# Freshly generated. Never carried from a development machine."
  echo "TIRO_JWT_SECRET=$(openssl rand -hex 32)"
  echo
  echo "# Empty means the ambient credentials: the instance role, if one is"
  echo "# attached. Fill these only if the instance has no role."
  echo "TIRO_S3_ACCESS_KEY="
  echo "TIRO_S3_SECRET_KEY="
  echo
  echo "# Carried from apps/api/.env."
} >> "$out"

carried=() missing=()
for key in "${CARRY[@]}"; do
  value="$(local_value "$key")"
  if [ -n "$value" ]; then
    printf '%s=%s\n' "$key" "$value" >> "$out"
    carried+=("$key")
  else
    missing+=("$key")
  fi
done

chmod 600 "$out"

echo "wrote $out (mode 600)"
echo
echo "carried from apps/api/.env:"
printf '  %s\n' "${carried[@]}"
if [ ${#missing[@]} -gt 0 ]; then
  echo
  echo "not set locally, so not carried (fine if you do not use them):"
  printf '  %s\n' "${missing[@]}"
fi
echo
echo "generated fresh: TIRO_JWT_SECRET"
echo "still yours to decide: TIRO_S3_ACCESS_KEY / TIRO_S3_SECRET_KEY,"
echo "  which stay empty if the instance has a role."
