# Mirrors crates/platform_core/mastery/src/python.rs. The boundary is JSON
# strings in, JSON strings out.

SPEC_VERSION: str

def default_params_json() -> str: ...
def apply_json(state_json: str | None, event_json: str, params_json: str) -> str: ...
def replay_json(events_json: str, params_json: str) -> str | None: ...
def supersede_json(events_json: str) -> str: ...
def view_json(state_json: str, now: int, params_json: str) -> str: ...

# The plain-language evidence trail (spec section 9): a JSON array of
# {"at": int, "text": str}, newest first, at most `limit` event lines plus a
# leading decay line when decay is the dominant story.
def evidence_trail_json(
    events_json: str, state_json: str, now: int, params_json: str, limit: int
) -> str: ...
